### PR TITLE
Drop support for unmaintained Julia 0.5

### PR DESCRIPTION
**Pull request by giordano**
Tests on Julia 0.7 are failing only because of missing
```julia
using DelimitedFiles, Printf
```
Should I use `Compat` to support this platform?

### CODE REVIEW

**Comment by kbarbary** [comment]
`using DelimitedFiles, Printf` is only required in tests, right? Would it work just to put

```julia
if VERSION < v"0.7-"
    using DelimitedFiles
    using Printf
end
```
in `runtests.jl`?

**Comment by giordano** [comment]
> `using DelimitedFiles, Printf` is only required in tests, right?

Exactly.

> Would it work just to put ....

No.  If I remember correctly, `using` is always executed, even in false branches.  I tried the following, adapted from `Compat.jl`:

```julia
if VERSION < v"0.7.0-DEV.3052"
    const Test = Base.Test
    const DelimitedFiles = Base.DataFmt
    const Printf = Base.Printf
else
    import Test, DelimitedFiles, Printf
end

using Test, DelimitedFiles, Printf
```

but I don't understand why Julia 0.6 says that `DelimitedFiles` variable is not defined :-/  I can't see what I'm missing.

**Comment by kbarbary** [comment]
I guess just put `Compat` in `test/REQUIRE` and use that, if it's easier!

**Comment by giordano** [comment]
My experience in using `test/REQUIRE` is that it greatly slows down running `Pkg.test()`.  Have you ever tried?

**Comment by kbarbary** [comment]
It would be fine to put `Compat` in the main REQUIRE file then. Whatever you find is best.

**Comment by giordano** [comment]
Ok, did it.  I also cleared a couple of other warnings in Julia 0.7.

**Comment by giordano** [comment]
I also added the constructor for
```julia
FK5Coords{e}(ra::Real, dec::Real)
```
which was commented in the code, because not possible in Julia 0.5.

**Pull request merged**
